### ISSUE TITLE
Artists with just one release don't get parsed

### ISSUE THREAD

**Issue by diemoschwarz** [Serhii-DV/bandcamp-to-discogs#75] opened 2024-09-22 19:45 UTC
Hi, this is a fantastic, immensely useful extension, thanks!   However, it seems to assume that the artist page contains a list of releases, but for artists with just one release bandcamp directly jumps to the release page, leading to blank data in the extension.

Example: https://cosseron-schwarz.bandcamp.com/ redirects to https://cosseron-schwarz.bandcamp.com/album/in-my-water

Cheers!

**Comment by Serhii-DV** [comment] 2024-09-24 08:59
Hi @diemoschwarz 
Thanks for the feedback. It looks like the issue is fixed with the latest version [0.13.1](https://github.com/Serhii-DV/bandcamp-to-discogs/releases/tag/v0.13.1). It works for me.
![image](https://github.com/user-attachments/assets/726cbf9a-b38f-4721-9648-5788cb85f423)

**Closed by Serhii-DV** 2024-09-24 08:59 UTC

**Comment by diemoschwarz** [comment] 2024-09-30 08:48
Works perfectly, thanks!
